### ISSUE TITLE
output of "validate syntax" cannot be shown in Tool Tip

### ISSUE THREAD

**Issue by vnoel** [textmate/python.tmbundle#57]
By default when I activate "validate syntax" on a random python file, the output is shown in a new window in HTML. This provides links to line numbers in the file, which is nice. However...

I'd like for errors and warnings to show up in a tooltip, as most syntax check bundles do, so I can run the syntax validation at each save. However, if I go to the Bundle Editor and select "Output : Show in Tool Tip", the tooltip shows the HTML code as text, whether I choose HTML or Text as the Format (see screenshot). I don't understand why you can select "HTML" as Format for the tooltip if the HTML cannot be rendered, but that's another concern.

<img width="1280" alt="screen shot 2016-10-10 at 21 44 47" src="https://cloud.githubusercontent.com/assets/731499/19249122/0cdd0dda-8f34-11e6-93c9-277587a9a7c7.png">

The nicest way to fix this would be to render the HTML in the tooltip, but I'm not sure how doable this is. It also might not be very useful, as the tooltip disappears as soon as you move the cursor. 

The other, easier option would be to fix the bundle so the "validate syntax" command behaves differently depending on what is selected for its "output": return HTML when "show in new window" is selected, and return text when "show in tool tip" is selected. I, however, have no idea how to start to implement this. Could anyone point me in the right direction?

**Comment by savetheclocktower** [comment]
I realize this is a year old, but here we go:

The output options are not meant to be changed by the person running the command; they're meant to be chosen among by whoever wrote the command. To show something in a tooltip you'll want to write a command that outputs plaintext.

To do what you want, you should install a tool like [`pep8`](https://pypi.python.org/pypi/pep8), then write a command that looks like this:

```sh
#!/bin/bash
ERRORS=$(pep8 "$TM_FILEPATH" | wc -l)
echo "$ERRORS errors"
```

With these settings:
* Scope Selector: source.python
* Semantic Class: callback.document.did-save
* Save: Nothing
* Input: Nothing (we're reading an environment variable to get the file)
* Output: Show in Tool Tip, Format: Text
* Caret Placement: (doesn't matter)

This code is an _extremely_ basic example. The `pep8` tool will return one line of output for each error, so counting the lines is one way to find out how many errors it found. The `callback.document.did-save` part is what will make it run upon save. (You'd want to make sure that `pep8` gets put somewhere in your `PATH` so that the command can locate it.)

If I were writing this command, I'd start with something as simple as the above. Then I'd make it exit without output if there were no errors. Then I'd actually start parsing the output of `pep8` so that I could put [gutter marks](https://github.com/textmate/textmate/blob/master/Applications/TextMate/about/Changes.md#2014-10-15-v20-alpha9575) on the lines that had errors.

I do most of this in my [ESLint bundle](https://github.com/savetheclocktower/ESLint.tmbundle), so you might find that useful as a reference. Of course, all my commands are written in Ruby. (You can write the command in Python, Ruby, or whatever else can go into a shebang.)
