### ISSUE TITLE
Proper folding of multi line function definitions

### ISSUE THREAD

**Issue by dwt** [textmate/python.tmbundle#64]
I tried looking at the grammar myself, but can't seem to figure out what is needed to make it accept multi line function definitions.

This is what I'm talking about:

```python
def foo(bar, baz,
             quoll, quaax):
    foo = bar
    baz = quaax
```

The problem is, that this function cannot be folded, which is quite annoying as it seems that textmate is not recognizing the function fully.

**Comment by sorbits** [comment]
Folding in TextMate is based on either recognizing lines as start/stop markers, or indent.

In your example two lines + indent indicates the folding point, this is not currently supported by TextMate.

Closing this issue as any change to accommodate more complex foldings would have to be done in TextMate rather than the Python bundle.

**Comment by dwt** [comment]
Could you please link to the TextMate bug where you are tracking this? I'd like to follow / help there.

**Comment by sorbits** [comment]
Sorry, but there is no public issue tracker for TextMate.

**Comment by dwt** [comment]
> Sorry, but there is no public issue tracker for TextMate.
> 

Well, then how about using the GitHub tracker? It seems perfect for features like this?

**Comment by sorbits** [comment]
Running a public issue tracker for TextMate leads to a lot of 
duplicates, support questions, and non-actionable feature requests.

Curating all that takes a lot of time with very few benefits (we already 
tried it).
