### ISSUE TITLE
Cleanup Whitespace fails with Anaconda Python V3.7.3

### ISSUE THREAD

**Issue by AndreaCogliati** [textmate/python.tmbundle#72]
I use Python V3.7.3 from Anaconda as my default Python interpreter in Textmate with the TM_PYTHON variable and Cleanup Whitespace fails with the following error:

```
Traceback (most recent call last):
  File "/Users/andreac/Library/Application Support/TextMate/Managed/Bundles/Python.tmbundle/Support/cleanup_whitespace.py", line 44, in <module>
    cleanup_whitespace()
  File "/Users/andreac/Library/Application Support/TextMate/Managed/Bundles/Python.tmbundle/Support/cleanup_whitespace.py", line 17, in cleanup_whitespace
    for linenum in xrange(len(lines)-1):
NameError: name 'xrange' is not defined
```

**Comment by sorbits** [comment]
Currently this is implemented as an “external” script that is called via `TM_PYTHON` instead of `/usr/bin/python` (so it would be unaffected by the value of this variable).

We can fix this, but is the command actually useful? I *think* this was added to add whitespace to blank lines for folding in TextMate 1.x to sort of work with Python, but TextMate 2 can fold based on indent, so there should be no need for this kludge.

IOW I suggest we just remove this command entirely. Any objections?

**Comment by sorbits** [comment]
> Doesn't it also fix mixed tabs and spaces in the source code?

Don’t know, but for this, we already have Convert Tabs to Spaces and vice versa in the Source bundle, so there is no reason for replicating this functionality.

Hint: Easy way to get at such actions is via <kbd>⌃⌘T</kbd>.

**Comment by posguy99** [comment]
This will blow up with **any** Python 3.x, because Python 3.x removes `xrange()`.

You can edit the script and change it to `range()`, if you want it to work.  Whether it's useful or not, I couldn't say.
